package neural.net;

import java.util.List;

/**
 *
 * @author Evan
 */
public class Run {
    private long    id;
    private double  momentum;
    private double  learningRate;
    private int     generations;
    private String  activation; // Sigmoid/Tanh
    private String  variant;    // Vanilla/QProp
    private String  train;      // file
    private String  test;       // file
    private List<Integer> shape;
    private List<Double> trainError;
    private List<Double> testError;
    
    //<editor-fold defaultstate="collapsed" desc="INNER CODE WAS AUTOGENERATED.">
    public long getId() {
        return id;
    }

    public String getTrain() {
        return train;
    }

    public void setTrain(String train) {
        this.train = train;
    }

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    
    public double getMomentum() {
        return momentum;
    }
    
    public void setMomentum(double momentum) {
        this.momentum = momentum;
    }
    
    public double getLearningRate() {
        return learningRate;
    }
    
    public void setLearningRate(double learningRate) {
        this.learningRate = learningRate;
    }
    
    public int getGenerations() {
        return generations;
    }
    
    public void setGenerations(int generations) {
        this.generations = generations;
    }
    
    public String getActivation() {
        return activation;
    }
    
    public void setActivation(String activation) {
        this.activation = activation;
    }
    
    public String getVariant() {
        return variant;
    }
    
    public void setVariant(String variant) {
        this.variant = variant;
    }
    
    public List<Integer> getShape() {
        return shape;
    }
    
    public void setShape(List<Integer> shape) {
        this.shape = shape;
    }
    
    public List<Double> getTrainError() {
        return trainError;
    }

    public void setTrainError(List<Double> trainError) {
        this.trainError = trainError;
    }

    public List<Double> getTestError() {
        return testError;
    }

    public void setTestError(List<Double> testError) {
        this.testError = testError;
    }
    //</editor-fold>
}
